trigger:
    - master

stages:
    - stage: Build
      pool:
       vmImage:"windows-latest"
      
      jobs:
          - job: Build
            steps:
                - task: DotNetCoreCLI@2
                  displayName: "Nuget Restore"
                  inputs:
                    projects: "**/*.csproj"
                    command: restore
                    arguments: --verbosity d
                
                      
                  
