
trigger:
    - master 

#These are global variables have 3 priority out of 5, 5 being the least
variables:
    buildStage: Build

stages:
- stage: $(buildStage)
  jobs:
  - job: $(buildStage)
    


