trigger:
    - master

pool:
    vmImage: "windows-latest"

stages:
    - stage: Build
      
      variables:
        buildPath: "Build"
        publishPath: "Publish"
      
      jobs:
          - job: Build
            steps:
                - task: DotNetCoreCLI@2
                  displayName: "Nuget Restore"
                  inputs:
                    projects: "**/*.csproj"
                    command: restore
                    arguments: --verbosity d
                
                - task: DotNetCoreCLI@2
                  displayName: "Dotnet Build"
                  inputs:
                      projects: "**/*.csproj"
                      command: build
                      arguments: --no-restore --configuration Release --verbosity d --output $(System.DefaultWorkingDirectory)
                
                - task: PublishPipelineArtifact@1
                  inputs:
                   ArtifactName: AppBuilt
                   targetPath: $(System.DefaultWorkingDirectory)/$(buildPath)
              

          - job: Publish
            dependsOn: Build
            condition: succeeded()

            steps:
                - task: DownloadPipelineArtifact@2
                  displayName: "Download Build"
                  inputs:
                   artifactName: AppBuilt
                   targetPath: $(System.DefaultWorkingDirectory)/$(buildPath)
                      

                - task: DotNetCoreCLI@2
                  displayName: "Publish"
                  inputs:
                    projects: "**/*.csproj"
                    command: publish
                    arguments: --no-build --no-restore --configuration Release --verbosity d --output $(System.DefaultWorkingDirectory)/$(publishPath)

                - task: PublishPipelineArtifact@1
                  condition: succeeded() 
                  displayName: "Publish Release"
                  inputs:
                      artifact: AppRelease
                      targetPath: $(System.DefaultWorkingDirectory)/$(publishPath)

    - stage: Deplopyment

      dependsOn: Build
      condition: succeeded()
      jobs:
          - deployment: AppSlotReleaseStarts
            environment: "ye-env"
            strategy:

            #Blue-Green deployment will be soon available which means that will be far more appriopriate then deploying it once :P 
             runOnce:
                 deploy:
                     steps:
                         - task: AzureWebApp@1
                           inputs:
                               azureSubscription: "appSlotDemoServiceConnection"
                               appType: webApp
                               appName: "DavidsDavidsonApp"
                               resourceGroupName: "AAPSD"
                               slotName: staging
                               deployToSlotOrASE: true        

                  
