trigger:
    - master

pool:
    vmImage: "windows-latest"

stages:
    - stage: Build
      
      jobs:
          - job: Build
            steps:
                - task: DotNetCoreCLI@2
                  displayName: "Nuget Restore"
                  inputs:
                    projects: "**/*.csproj"
                    command: restore
                    arguments: --verbosity d
                
                - task: DotNetCoreCLI@2
                  displayName: "Dotnet Build"
                  inputs:
                      projects: "**/*.csproj"
                      command: build
                      arguments: --no-restore --configuration Release --verbosity d
                
                - task: PublishPipelineArtifact@1
                  inputs:
                   ArtifactName: AppSlot
                   targetPath: $(System.DefaultWorkingDirectory)

                      

          - job: Publish
            dependsOn: Build
            condition: succeeded()

            steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                   artifactName: AppSlot
                      

                - task: DotNetCoreCLI@2
                  displayName: "Publish"
                  inputs:
                    projects: "$(Pipeline.Workspace)/AppSlot/**/*.csproj"
                    command: publish
                    arguments: --no-build --no-restore --configuration Release --verbosity d --output $(Build.SourcesDirectory)

                
                  
